-- Таблица sales из m250603_214145_create_sales_table
CREATE TABLE IF NOT EXISTS sales (
                                     id_sale SERIAL PRIMARY KEY,
                                     id_user INT NOT NULL,
                                     realizationreport_id VARCHAR(255),
    date_from TIMESTAMP,
    date_to TIMESTAMP,
    subject_name VARCHAR(500),
    nm_id VARCHAR(255),
    brand_name VARCHAR(500),
    quantity VARCHAR(255),
    retail_price VARCHAR(255),
    retail_amount VARCHAR(255),
    sale_percent VARCHAR(255),
    commission_percent VARCHAR(255),
    office_name VARCHAR(500),
    supplier_oper_name VARCHAR(500),
    retail_price_withdisc_rub VARCHAR(255),
    delivery_amount VARCHAR(255),
    return_amount VARCHAR(255),
    delivery_rub VARCHAR(255),
    gi_box_type_name VARCHAR(500),
    product_discount_for_report VARCHAR(255),
    supplier_promo VARCHAR(500),
    rid VARCHAR(500),
    ppvz_spp_prc VARCHAR(255),
    ppvz_kvw_prc_base VARCHAR(255),
    ppvz_kvw_prc VARCHAR(255),
    sup_rating_prc_up VARCHAR(255),
    is_kgvp_v2 VARCHAR(255),
    ppvz_sales_commission VARCHAR(255),
    ppvz_for_pay VARCHAR(255),
    ppvz_reward VARCHAR(255),
    acquiring_fee VARCHAR(255),
    acquiring_bank VARCHAR(500),
    ppvz_vw VARCHAR(255),
    ppvz_vw_nds VARCHAR(255),
    bonus_type_name VARCHAR(500),
    site_country VARCHAR(500),
    penalty VARCHAR(255),
    additional_payment VARCHAR(255),
    rebill_logistic_cost VARCHAR(255),
    rebill_logistic_org VARCHAR(500),
    kiz VARCHAR(255),
    create_dt TIMESTAMP,
    currency_name VARCHAR(500)
    );

CREATE INDEX idx_sales_id_user ON sales(id_user);