<script setup>

</script>

<template>
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">
            Пользователи                    </h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <div class="content">


    <div id="content" class="output" style="overflow-y: auto">

      <div id="w0" style="width: 1800px;"><div class="summary">Показаны записи <b>1-35</b> из <b>35</b>.</div>
        <table class="table table-striped table-bordered"><thead>
        <tr><th><a href="/user?sort=id_user" data-sort="id_user">ID</a></th><th><a href="/user?sort=username" data-sort="username">Логин</a></th><th><a href="/user?sort=email" data-sort="email">email</a></th><th><a href="/user?sort=name" data-sort="name">Имя</a></th><th><a href="/user?sort=block" data-sort="block">Заблокирован</a></th><th><a href="/user?sort=pro" data-sort="pro">Про аккаунт</a></th><th><a href="/user?sort=admin" data-sort="admin">Админ</a></th><th>Телефон</th><th>Налоги %</th><th><a class="desc" href="/user?sort=created_at" data-sort="created_at">Создан</a></th><th><a href="/user?sort=updated_at" data-sort="updated_at">Последнее обновление</a></th><th><a href="/user?sort=last_login" data-sort="last_login">Последняя авторизация</a></th><th><a href="/user?sort=wb_key" data-sort="wb_key">Ключ WB</a></th><th>Действие</th></tr>
        </thead>
          <tfoot>
          <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
          </tfoot>
          <tbody>
          <tr data-key="46"><td>46</td><td>oaOtlQlllSZHGtbfQpGtoKy</td><td>adodoheyenu865@gmail.com</td><td>ttYRnpsdyFxdGELD</td><td>0</td><td>1</td><td>0</td><td>2350373155</td><td>0</td><td>2025-12-21 17:48:59</td><td>2025-12-21 17:49:24</td><td><span style="color: red;">2025-12-21 17:48:59</span></td><td>jtgVJhwQUxcJctJxU</td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=46&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=46&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=46&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=46&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="45"><td>45</td><td>IKgfehmonfrjkGJE</td><td>ohobucehemic09@gmail.com</td><td>ZCVHpASbCVoDJMsqmkzY</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-12-04 18:09:53</td><td>2025-12-04 18:09:53</td><td><span style="color: red;">2025-12-04 18:09:53</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=45&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=45&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=45&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=45&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="44"><td>44</td><td>koMEpDdCATNcWOnmDC</td><td>ekurihap21@gmail.com</td><td>ToggzJINTWGqAuptNFk</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-12-01 00:34:45</td><td>2025-12-01 00:34:45</td><td><span style="color: red;">2025-12-01 00:34:45</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=44&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=44&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=44&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=44&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="43"><td>43</td><td>ahypkZNgNXPXKBcBZehQ</td><td>hoxotegij82@gmail.com</td><td>zQsWWIIhtIqvaQEmYlmGX</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-11-27 15:55:02</td><td>2025-11-27 15:55:02</td><td><span style="color: red;">2025-11-27 15:55:02</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=43&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=43&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=43&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=43&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="42"><td>42</td><td>kAErzbiYqVXwxGgnrS</td><td>wejavuyuya86@gmail.com</td><td>TMmCnYYObMvBKmGZvH</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-11-23 11:39:48</td><td>2025-11-23 11:39:48</td><td><span style="color: red;">2025-11-23 11:39:48</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=42&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=42&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=42&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=42&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="41"><td>41</td><td>elen/esayan04@mail.com</td><td>elen.esayan04@gmail.com</td><td>Элен</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-10-21 11:10:01</td><td>2025-10-21 11:10:01</td><td><span style="color: red;">2025-10-21 11:10:01</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=41&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=41&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=41&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=41&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="40"><td>40</td><td>ludabar</td><td>luda.sharshenova@gmail.com</td><td>Людмила</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-10-01 16:30:58</td><td>2025-10-01 16:30:58</td><td><span style="color: red;">2025-10-01 16:30:58</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=40&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=40&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=40&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=40&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="39"><td>39</td><td>aziz_ov</td><td>aziz-ov@yandex.ru</td><td>Азиз</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-10-01 12:20:58</td><td>2025-10-01 12:20:58</td><td><span style="color: red;">2025-10-01 14:49:01</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=39&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=39&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=39&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=39&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="37"><td>37</td><td>Shraunsxz</td><td>yasmamadoo@bubuk.site</td><td>Shraunsxz</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-09-11 00:50:18</td><td>2025-09-11 00:50:18</td><td><span style="color: red;">2025-09-11 00:50:18</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=37&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=37&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=37&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=37&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="36"><td>36</td><td>marsyanya10</td><td>marsyanya10@mail.ru</td><td>Татьяна</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>7</td><td>2025-08-15 03:28:37</td><td>2025-08-15 03:28:37</td><td><span style="color: red;">2025-08-15 03:28:37</span></td><td>eyJhbGciOiJFUzI1NiIsImtpZCI6IjIwMjUwNTIwdjEiLCJ...</td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=36&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=36&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=36&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=36&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="35"><td>35</td><td>Mfuehudwj hiwjswdwidjwidji jdiwjswihdfeufhiwj ijdi</td><td>nomin.momin+381c7@mail.ru</td><td>Mfuehudwj hiwjswdwidjwidji jdiwjswi</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-08-01 08:02:19</td><td>2025-08-01 08:02:19</td><td><span style="color: red;">2025-08-01 08:02:19</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=35&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=35&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=35&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=35&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="34"><td>34</td><td>ViagSimebaib</td><td>o81234842@gmail.com</td><td>ViagSimebaib</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-06-28 03:54:59</td><td>2025-06-28 03:54:59</td><td><span style="color: red;">2025-06-28 03:54:59</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=34&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=34&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=34&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=34&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="33"><td>33</td><td>MerleDor</td><td>inb@bubuk.site</td><td>MerleDor</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-05-06 17:11:39</td><td>2025-05-06 17:11:39</td><td><span style="color: red;">2025-05-06 17:11:39</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=33&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=33&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=33&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=33&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="30"><td>30</td><td>L1nk13</td><td>proskurin.es@mail.ru</td><td>Егор Проскурин</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-04-03 22:45:20</td><td>2025-04-03 22:45:20</td><td><span style="color: red;">2025-04-03 22:45:20</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=30&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=30&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=30&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=30&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="29"><td>29</td><td>BexlasriG</td><td>zaharnosov@readyneck.ru</td><td>BexlasriG</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-03-30 20:37:18</td><td>2025-03-30 20:37:18</td><td><span style="color: red;">2025-03-30 20:37:18</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=29&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=29&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=29&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=29&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="28"><td>28</td><td>Robertbuipt</td><td>father@prostpro.fun</td><td>Robertbuipt</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-03-06 19:28:27</td><td>2025-03-06 19:28:27</td><td><span style="color: red;">2025-03-06 19:28:27</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=28&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=28&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=28&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=28&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="26"><td>26</td><td>Юлияя</td><td>abdurahmanovayulya52@gmail.com</td><td>Юлия</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-01-29 11:51:23</td><td>2025-01-29 11:51:23</td><td><span style="color: red;">2025-01-29 11:51:23</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=26&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=26&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=26&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=26&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="25"><td>25</td><td>Plnadya1995</td><td>plastinina974@gmail.com</td><td>Надежда</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-01-29 09:02:40</td><td>2025-01-29 09:02:40</td><td><span style="color: red;">2025-01-29 09:02:40</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=25&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=25&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=25&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=25&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="24"><td>24</td><td>tatkov88</td><td>reg2088@bk.ru</td><td>Таня</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-01-27 22:43:17</td><td>2025-01-27 22:43:17</td><td><span style="color: red;">2025-01-27 22:43:17</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=24&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=24&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=24&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=24&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="23"><td>23</td><td>mazeta</td><td>mazeta@mail.ru</td><td>Евгения </td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-01-27 14:53:42</td><td>2025-01-27 14:53:42</td><td><span style="color: red;">2025-01-27 14:53:42</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=23&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=23&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=23&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=23&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="22"><td>22</td><td>IrinaMP</td><td>Irinakuljukina@mail.ru</td><td>Ирина</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-01-26 19:10:21</td><td>2025-01-26 19:10:21</td><td><span style="color: red;">2025-01-26 19:10:21</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=22&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=22&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=22&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=22&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="21"><td>21</td><td>svet7422@yandex.ru</td><td>svet7422@yandex.ru</td><td>Алексей </td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-01-24 01:44:32</td><td>2025-01-24 01:44:32</td><td><span style="color: red;">2025-01-24 01:44:32</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=21&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=21&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=21&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=21&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="20"><td>20</td><td>wbros</td><td>user_es@mail.ru</td><td>Вячеслав</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>7</td><td>2025-01-16 10:29:54</td><td>2025-01-16 10:29:54</td><td><span style="color: red;">2025-01-16 10:29:54</span></td><td>eyJhbGciOiJFUzI1NiIsImtpZCI6IjIwMjQxMjE3djEiLCJ...</td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=20&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=20&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=20&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=20&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="19"><td>19</td><td>annabadamshina1996@mail.ru</td><td>annabadamshina1996@mail.ru</td><td>Анна </td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-01-11 18:38:53</td><td>2025-01-11 18:38:53</td><td><span style="color: red;">2025-01-11 18:38:53</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=19&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=19&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=19&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=19&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="18"><td>18</td><td>wvsl07!-q</td><td>x3ls0@mail.ru</td><td>Taya</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-01-06 20:42:20</td><td>2025-01-06 20:42:20</td><td><span style="color: red;">2025-01-06 20:42:20</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=18&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=18&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=18&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=18&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="17"><td>17</td><td>Smoow</td><td>rrubcov29@gmail.com</td><td>Роман</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2025-01-04 17:38:52</td><td>2025-01-04 17:38:52</td><td><span style="color: red;">2025-01-04 17:38:52</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=17&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=17&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=17&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=17&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="16"><td>16</td><td>berkut25</td><td>berkut25@mail.ru</td><td>Дмитрий</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>6</td><td>2024-12-30 23:29:46</td><td>2024-12-30 23:29:46</td><td><span style="color: red;">2024-12-30 23:29:46</span></td><td>eyJhbGciOiJFUzI1NiIsImtpZCI6IjIwMjQxMjE3djEiLCJ...</td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=16&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=16&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=16&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=16&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="14"><td>14</td><td>alyona-strinkevich</td><td>alyona-strinkevich@mail.ru</td><td>Елена</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2024-12-18 11:39:50</td><td>2024-12-18 11:39:50</td><td><span style="color: red;">2024-12-18 22:27:53</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=14&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=14&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=14&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=14&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="12"><td>12</td><td>wbwbwb</td><td>vernicsgo@gmail.com</td><td>алекс</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>6</td><td>2024-12-17 14:23:15</td><td>2024-12-17 14:23:15</td><td><span style="color: red;">2024-12-18 22:27:53</span></td><td>eyJhbGciOiJFUzI1NiIsImtpZCI6IjIwMjQxMTE4djEiLCJ...</td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=12&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=12&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=12&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=12&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="11"><td>11</td><td>DallasMem</td><td>filippignatev@roundself.ru</td><td>DallasMem</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2024-12-14 16:01:20</td><td>2024-12-14 16:01:20</td><td><span style="color: red;">2024-12-18 22:27:53</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=11&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=11&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=11&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=11&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="10"><td>10</td><td>polinarodites</td><td>polinarodites04@gmail.com</td><td>Полина</td><td>0</td><td>1</td><td>0</td><td>+79530203758</td><td>7</td><td>2024-12-13 10:17:52</td><td>2024-12-13 10:17:52</td><td><span style="color: red;">2024-12-18 22:27:53</span></td><td>e</td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=10&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=10&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=10&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=10&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="9"><td>9</td><td>and921</td><td>and921@bk.ru</td><td>Андрей </td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2024-12-10 11:12:57</td><td>2024-12-10 11:12:57</td><td><span style="color: red;">2024-12-18 22:27:53</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=9&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=9&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=9&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=9&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="8"><td>8</td><td>Кирилл</td><td>info@sedovkir.ru</td><td>Кирилл</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2024-12-06 10:44:04</td><td>2024-12-06 10:44:04</td><td><span style="color: red;">2024-12-18 22:27:53</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=8&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=8&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=8&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=8&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="6"><td>6</td><td>Вадим</td><td>lvs757@yandex.ru</td><td>Вадим</td><td>0</td><td>1</td><td>0</td><td><span class="not-set">(не задано)</span></td><td>0</td><td>2024-12-04 15:07:47</td><td>2024-12-04 15:07:47</td><td><span style="color: red;">2024-12-18 22:27:53</span></td><td><span class="not-set">(не задано)</span></td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=6&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-success btn-xs" href="/user/activate-pro?params%5Bid_user%5D=6&amp;params%5Bset-admin%5D=2" style="margin-bottom: 2px;">admin - выдать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=6&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=6&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          <tr data-key="2"><td>2</td><td>admin</td><td>maksimrozette@gmail.com</td><td>System</td><td>0</td><td>1</td><td>1</td><td>+79937799526</td><td>5</td><td>2024-11-16 17:11:31</td><td>2025-10-03 17:02:34</td><td><span style="color:#fff3cd">2026-01-15 22:15:27</span></td><td>eyJhbGciOiJFUzI1NiIsImtpZCI6IjIwMjUwNTIwdjEiLCJ...</td><td class="text-left"><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=2&amp;params%5Bset-pro%5D=0" style="margin-bottom: 2px;">pro - забрать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=2&amp;params%5Bset-admin%5D=0" style="margin-bottom: 2px;">admin - забрать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=2&amp;params%5Bset-block%5D=1" style="margin-bottom: 2px;" onclick="confirmBlock(event)">заблокировать</a><br><a class="btn btn-danger btn-xs" href="/user/activate-pro?params%5Bid_user%5D=2&amp;params%5Bset-del-user%5D=1" style="margin-bottom: 2px;" onclick="confirmDel(event)">удалить</a><br></td></tr>
          </tbody></table>
        <nav id="w1"></nav></div></div>
    <!-- /.container-fluid -->
  </div>
</template>
<script>
function confirmDel(e) {
  if(confirm('Вы уверены что хотите удалить пользователя ?')){
    return true;
  }else{
    e.preventDefault();
  }
}

function confirmBlock(e) {
  if(confirm('Вы уверены что хотите заблокировать пользователя ?')){
    return true;
  }else{
    e.preventDefault();
  }
}
</script>
<style scoped>

</style>